// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LiveCoder.Extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "LiveCoderExtension.f4f2b903-2560-435c-bf24-a038c83ed7b2";
        public const string Name = "Live Coder";
        public const string Description = @"Helps hold coding demos in Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.11.0";
        public const string Author = "Zoran Horvat";
        public const string Tags = "";
    }
}
